# Generated by Django 3.1.4 on 2021-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210116_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
