# Generated by Django 3.1.4 on 2021-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
