# Generated by Django 3.1.4 on 2021-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210117_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderate',
            field=models.IntegerField(choices=[(0, 'Removed'), (1, 'Allowed')], default=1),
        ),
    ]
