# Generated by Django 3.1.4 on 2021-01-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_moderate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='allowed',
        ),
    ]
