# Generated by Django 3.1.4 on 2021-01-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moderate',
        ),
    ]
