# Generated by Django 4.0.1 on 2022-01-11 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves',
            field=models.ManyToManyField(related_name='post_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
